/* NursingSim - student page only (v30). Adds "Open Patient" (the file the instructor shares) and "My Results".
   Loaded by student.html (generated by make-student.js). Depends on app.js globals validateCaseInput, renderPatient, simulationTime, refreshSimulationView. */
(() => {
  'use strict';
  const actions = document.querySelector('.top-actions'); if (!actions) return;
  const input = document.createElement('input'); input.type = 'file'; input.accept = 'application/json,.json'; input.className = 'hidden'; input.id = 'stuFile';
  const open = document.createElement('button'); open.className = 'primary-button'; open.id = 'stuOpenBtn'; open.textContent = 'Open Patient';
  const res = document.createElement('button'); res.className = 'top-link top-button'; res.id = 'stuResultsBtn'; res.textContent = 'My Results';
  actions.appendChild(res); actions.appendChild(open); document.body.appendChild(input);
  open.addEventListener('click', () => input.click());
  res.addEventListener('click', () => NSResults.openStudentDialog());

  input.addEventListener('change', async ev => {
    const f = ev.target.files[0]; ev.target.value = ''; if (!f) return;
    try {
      const parsed = JSON.parse(await f.text());
      const canon = parsed && parsed.canonical ? parsed.canonical : parsed;
      if (!canon || !canon.patient) throw new Error('This file is not a NursingSim patient.');
      if (typeof currentCanonicalCase !== 'undefined' && currentCanonicalCase && currentCanonicalCase.patient && !confirm('Open this patient? Your work on the patient you have open now will be replaced.')) return;
      const report = validateCaseInput(canon);
      if (report.errors > 0) throw new Error('This patient file has problems and cannot be opened. Ask your instructor for a new copy.');
      renderPatient(report.canonical);
      if (parsed.simulationTime && report.canonical.timeline && String(report.canonical.timeline.simulationStart) !== String(parsed.simulationTime)) { /* start time comes from the file */ }
    } catch (e) { alert(e.message || 'Could not open that file.'); }
  });
})();
