/* Medical primary diagnoses, misc: acute kidney injury with hyperkalemia, cellulitis, alcohol withdrawal, seizure, hyponatremia. */
(() => {
  const U = NS.util, C = NS.C;
  const sc = (arr, f) => arr.map(([h, v]) => [h, Math.round(v * f * 100) / 100]);
  const lab = (code, def) => { NS.LABS.C[code] = NS.LABS.C[code] || def; };
  lab('MCV', { cat: 'CBC', units: 'fL', ref: [80, 100], dec: 0, base: 90 });
  
  // ============================================================================ ACUTE KIDNEY INJURY WITH HYPERKALEMIA
  NS.PRIMARY.aki = {
    key: 'aki', label: 'Acute Kidney Injury with Hyperkalemia', group: 'Medical', cat: 'Renal / Fluid & Electrolytes', typicalLOS: [3, 5],
    desc: 'Prerenal AKI from volume depletion plus NSAID/ACE inhibitor, K 6.4 with ECG changes. Day 1: calcium, insulin/dextrose, albuterol, fluids, nephrology. Day 2-3: creatinine peaks, then recovers. Day 4-5: discharge. Day 7+: ATN with slow recovery.',
    build(ctx) {
      const comp = ctx.L >= 7, esrd = ctx.renal === 'esrd', ckd = ctx.renal === 'ckd3';
      const kCr = esrd ? 0.15 : 1, kK = esrd ? 0.6 : ckd ? 0.8 : 1, kB = esrd ? 0.25 : 1;
      const uopGoal = Math.round(ctx.weightKg * 0.5);
      const nsaid = 'ibuprofen 600 mg three times daily for back pain';
      const spec = {
        primaryTeam: 'hospitalist', typicalLOS: [3, 5], noAutoProlonged: comp,
        problem: { name: 'Acute kidney injury with hyperkalemia', details: esrd ? 'Hyperkalemia with volume depletion after missed hemodialysis in a patient with ESRD.' : 'Prerenal acute kidney injury (volume depletion, NSAID, ACE inhibitor if prescribed) with hyperkalemia and ECG changes.' },
        chief: esrd ? 'Weakness and palpitations after missed dialysis' : 'Weakness, nausea and decreased urine output',
        hpi: esrd
          ? `${ctx.age}-year-old ${ctx.sex.toLowerCase()} with ESRD on hemodialysis who missed the last two sessions (transportation problems), now with generalized weakness, nausea and palpitations. Reports eating bananas, oranges and tomatoes this week. Minimal urine output at baseline. ED potassium 6.4 mmol/L with peaked T waves; no chest pain or dyspnea.`
          : `${ctx.age}-year-old ${ctx.sex.toLowerCase()} with 3 days of vomiting and diarrhea and poor oral intake, taking ${nsaid}${ctx.has('htn') ? ' and lisinopril 20 mg daily' : ''}. Presents with generalized weakness, muscle cramps, nausea, lightheadedness on standing and markedly decreased urine output (dark, scant). No flank pain, hematuria, dysuria, fever or contrast exposure. ED: BP 98/58, HR 102, creatinine markedly above baseline (baseline ${ckd ? 'about 1.8' : 'normal'}), potassium 6.4 mmol/L with peaked T waves.`,
        ros: 'Positive for weakness, muscle cramps, nausea, vomiting, diarrhea, thirst, dizziness on standing and decreased urine output. Negative for chest pain, dyspnea, syncope, hematuria, flank pain, rash, joint swelling and fever.',
        keyLabs: ['Potassium', 'Creatinine', 'BUN', 'CO2', 'Sodium', 'Glucose', 'Phosphorus', 'Calcium'], hpLabs: ['Potassium', 'Creatinine', 'BUN', 'CO2', 'Sodium', 'Chloride', 'Glucose', 'Phosphorus', 'Magnesium', 'Calcium', 'Creatine kinase'],
        isolation: 'None', fluidSensitive: false, fallRiskBoost: 1,
        flags: { npo: [], hypotension: [[0, comp ? 260 : 110]] },
        vitals: [
          { h: 0, temp: 98.8, hr: 102, sbp: 98, dbp: 58, rr: 20, spo2: 97, pain: 2, o2: 'Room air' }, { h: 3, temp: 98.6, hr: 94, sbp: 106, dbp: 62, rr: 18, spo2: 97, pain: 2 },
          { h: 8, temp: 98.6, hr: 90, sbp: 110, dbp: 66, rr: 18, spo2: 98, pain: 1 }, { h: 24, temp: 98.4, hr: 84, sbp: 116, dbp: 70, rr: 16, spo2: 98, pain: 1 },
          { h: 48, temp: 98.4, hr: 80, sbp: comp ? 128 : 120, dbp: comp ? 78 : 72, rr: 16, spo2: 98, pain: 0 }, { h: 96, temp: 98.2, hr: 76, sbp: comp ? 132 : 122, dbp: comp ? 80 : 74, rr: 16, spo2: 98, pain: 0 }
        ],
        labs: {
          Potassium: { add: sc(comp ? [[0, 2.3], [0.9, 2.3], [2.4, 1.2], [4, 1.45], [7, 1.5], [11, 1.25], [18, 1.0], [30, 0.85], [50, 0.6], [74, 0.4], [120, 0.2], [168, 0.05]] : [[0, 2.3], [0.9, 2.3], [2.4, 1.2], [4, 1.45], [7, 1.5], [11, 1.2], [18, 0.9], [30, 0.65], [50, 0.35], [74, 0.15], [100, 0]], kK) },
          Creatinine: { add: sc(comp ? [[0, 1.9], [24, 2.6], [48, 2.9], [96, 2.85], [120, 2.5], [144, 1.9], [168, 1.3], [216, 0.7], [300, 0.25]] : [[0, 1.9], [12, 2.35], [24, 2.55], [36, 2.3], [48, 1.75], [72, 0.95], [96, 0.4], [120, 0.12]], kCr) },
          BUN: { add: sc(comp ? [[0, 46], [24, 56], [48, 66], [96, 68], [120, 58], [168, 36], [216, 18], [300, 6]] : [[0, 46], [12, 54], [24, 54], [48, 38], [72, 18], [96, 7], [120, 2]], kB) },
          CO2: { add: comp ? [[0, -10], [24, -8], [96, -6], [168, -3], [240, 0]] : [[0, -10], [10, -8], [24, -5], [48, -3], [72, -1], [96, 0]] }, Chloride: { add: [[0, 3], [48, 2], [96, 0]] }, Sodium: { add: [[0, -2], [24, 0]] },
          Phosphorus: { add: comp ? [[0, 2.0], [48, 2.6], [120, 2.4], [200, 1.0], [300, 0]] : [[0, 2.0], [24, 2.4], [60, 1.5], [96, 0.3], [120, 0]] },
          Calcium: { add: [[0, -0.8], [48, -0.6], [96, -0.2], [140, 0]] }, Magnesium: { add: [[0, 0.35], [48, 0.2], [96, 0]] },
          Hemoglobin: { add: [[0, 0.9], [24, -0.4], [72, -1.0], [140, -1.0]] }, WBC: { add: [[0, 2.0], [24, 0.5], [48, 0]] },
          Glucose: { add: [[0, 12], [1, 10], [2, 30], [3, 0], [4, -14], [5, -10], [8, 0]] }, 'Creatine kinase': { abs: [[0.5, 160]] }
        },
        labSchedule: [
          { h: 0.5, codes: ['Phosphorus', 'Magnesium', 'Creatine kinase'] }, { h: 2.5, codes: ['Potassium', 'Glucose'] }, { h: 3.7, codes: ['Glucose'] }, { h: 5, codes: ['Glucose'] },
          { h: 6.5, codes: ['Potassium', 'Glucose', 'CO2'] }, { h: 11, codes: ['Potassium', 'CO2', 'Creatinine', 'BUN'] }, { h: 17, codes: ['Potassium', 'Glucose'] }, { daily: true, codes: ['Phosphorus'] }
        ],
        quals: esrd ? [] : [
          { h: 1.0, category: 'Urinalysis', code: 'Urinalysis - specific gravity', value: '1.026', reference: '1.005-1.030', specimen: 'Urine' },
          { h: 1.0, category: 'Urinalysis', code: 'Urinalysis - protein', value: 'Trace', reference: 'Negative', flag: 'Abnormal', specimen: 'Urine' },
          { h: 1.0, category: 'Urinalysis', code: 'Urinalysis - blood', value: 'Negative', reference: 'Negative', specimen: 'Urine' },
          { h: 1.0, category: 'Urinalysis', code: 'Urinalysis - microscopy', value: 'Occasional hyaline casts; no RBC, WBC or granular casts', reference: 'None', specimen: 'Urine' },
          { h: 1.5, category: 'Urine chemistry', code: 'Urine sodium', value: '16', units: 'mmol/L', reference: 'Prerenal: <20', flag: 'Low', specimen: 'Urine' },
          { h: 1.5, category: 'Urine chemistry', code: 'Urine creatinine', value: '140', units: 'mg/dL', reference: '', specimen: 'Urine' },
          { h: 1.5, category: 'Urine chemistry', code: 'Urine osmolality', value: '540', units: 'mOsm/kg', reference: '>500 prerenal', specimen: 'Urine' },
          { h: 1.5, category: 'Urine chemistry', code: 'Fractional excretion of sodium (FeNa)', value: '0.3', units: '%', reference: '<1% prerenal; >2% ATN', specimen: 'Urine/Blood' },
          ...(comp ? [
            { h: 30, category: 'Urinalysis', code: 'Urinalysis - microscopy (repeat)', value: 'Granular ("muddy brown") casts and renal tubular epithelial cells', reference: 'None', flag: 'Abnormal', specimen: 'Urine' },
            { h: 30, category: 'Urine chemistry', code: 'Urine sodium', value: '58', units: 'mmol/L', reference: 'Prerenal: <20', flag: 'High', specimen: 'Urine' },
            { h: 30, category: 'Urine chemistry', code: 'Fractional excretion of sodium (FeNa)', value: '2.4', units: '%', reference: '<1% prerenal; >2% ATN', flag: 'High', specimen: 'Urine/Blood' }
          ] : [])
        ],
        events: [
          { type: 'cardiology', h: 0.6, study: '12-lead ECG', label: 'ECG: hyperkalemia changes', indication: 'Weakness, K 6.4 mmol/L', impression: `${ctx.has('afib') ? 'Atrial fibrillation, rate 90' : 'Sinus rhythm, rate 88'}; tall peaked T waves V2-V5, PR interval 212 ms, QRS 96 ms. Consistent with hyperkalemia; no QRS widening or sine wave.` },
          { type: 'cardiology', h: 3.0, study: '12-lead ECG (repeat)', label: 'Repeat ECG after treatment', indication: 'Follow-up of hyperkalemic ECG changes', impression: `${ctx.has('afib') ? 'Atrial fibrillation, rate 82' : 'Normal sinus rhythm, rate 80'}; T waves less peaked, PR 176 ms, QRS 92 ms. Improvement of hyperkalemic changes.` },
          { type: 'consult', h: 3.5, service: 'Nephrology', author: 'nephrology', reason: esrd ? 'Hyperkalemia with ECG changes after missed dialysis' : 'AKI with hyperkalemia (K 6.4)', label: 'Nephrology consulted',
            recommendation: esrd ? 'Urgent hemodialysis today for hyperkalemia; continue temporizing measures; low-potassium renal diet; reinforce dialysis adherence and transportation plan with social work.'
              : `Prerenal AKI from volume depletion with NSAID${ctx.has('htn') ? ' and ACE inhibitor' : ''} contribution. Isotonic fluids, treat hyperkalemia, stop nephrotoxins, renal ultrasound, urine studies, strict I&O with goal urine output at least ${uopGoal} mL/hr, daily weights. No current indication for dialysis (no refractory hyperkalemia, acidosis, volume overload or uremic symptoms); reassess if oliguria persists.${comp ? ' Urine sediment shows muddy brown casts: evolving ATN; avoid volume overload, furosemide trial, expect slow recovery.' : ''}` },
          { type: 'transfer', h: 4.0, label: 'Admitted to the medical unit with telemetry', text: 'Transferred from the ED to the medical unit on continuous cardiac monitoring.' },
          ...(esrd ? [] : [{ type: 'imaging', h: 4.5, study: 'Renal and bladder ultrasound', modality: 'Ultrasound', indication: 'AKI: exclude obstruction', findings: ckd ? 'Both kidneys are small (9.4 cm) with increased cortical echogenicity. No hydronephrosis, stones or mass. Bladder is not distended; post-void residual about 40 mL.' : 'Normal-sized kidneys (11 cm right, 10.8 cm left) with normal echogenicity. No hydronephrosis, stones or mass. Bladder is not distended; post-void residual about 40 mL.', impression: ckd ? 'Chronic medical renal disease changes. No obstruction.' : 'No hydronephrosis or obstruction. Normal-appearing kidneys.' }]),
          ...(esrd ? [{ type: 'procedure', h: 6, duration: 3.5, name: 'Hemodialysis (urgent, 3.5 h)', label: 'Urgent hemodialysis for hyperkalemia', dialysis: true, ufRemoved: 500, by: 'nephrology', service: 'Nephrology' }] : [])
        ],
        meds: [
          { key: 'calcium_gluconate', name: 'calcium gluconate 10% injection', dose: '1 g (10 mL)', route: 'IV', freq: 'once', startH: 0.8, volume: 100, cls: 'Electrolyte / cardiac membrane stabilizer', info: 'Infuse over 10 minutes on continuous ECG monitoring; protects the heart but does NOT lower potassium. Effect lasts 30-60 minutes. Stop if bradycardia. Do not mix with sodium bicarbonate. Use a patent IV (tissue injury if infiltrated).', monitor: ['HR', 'BP', 'K'], indication: 'Hyperkalemia with ECG changes (cardiac membrane stabilization)', by: 'ed', highAlert: true },
          { key: 'calcium_gluconate_repeat', name: 'calcium gluconate 10% injection', dose: '1 g (10 mL)', route: 'IV', freq: 'once', startH: 1.4, volume: 100, cls: 'Electrolyte / cardiac membrane stabilizer', info: 'Repeat dose if ECG changes persist 5 minutes after the first dose. Continuous ECG monitoring.', monitor: ['HR', 'BP'], indication: 'Persistent hyperkalemic ECG changes', by: 'ed', highAlert: true },
          { key: 'insulin_regular_k', name: 'insulin regular (HUMULIN R) injection', dose: '10 units', route: 'IV', freq: 'once', startH: 1.0, cls: 'Short-acting insulin', info: 'HIGH-ALERT. Shifts potassium into cells (onset 15-30 min, lasts 4-6 h). Give with dextrose; check glucose BEFORE and every hour for 6 hours (risk of delayed hypoglycemia, higher in kidney injury).', monitor: ['K', 'Glucose'], hold: 'Verify pre-dose glucose; if below 70 mg/dL call provider before giving. Dextrose is omitted only if glucose is 250 or higher.', indication: 'Hyperkalemia (intracellular shift)', by: 'ed', highAlert: true, renal: { ckd3: { dose: '5 units', note: 'Reduced dose (5 units) for kidney disease to lower hypoglycemia risk.' }, esrd: { dose: '5 units', note: 'Reduced dose (5 units) for ESRD to lower hypoglycemia risk.' } } },
          { key: 'dextrose_50', name: 'dextrose 50% injection', dose: '25 g (50 mL)', route: 'IV', freq: 'once', startH: 1.0, cls: 'Carbohydrate', info: 'Give with the insulin over 5 minutes through a patent IV (vesicant). Check glucose hourly.', monitor: ['Glucose'], indication: 'Prevent insulin-induced hypoglycemia', by: 'ed' },
          { key: 'd10w_infusion', name: 'dextrose 10% in water infusion', dose: '50 mL/hr', rate: '50 mL/hr', mlPerHr: 50, route: 'IV', freq: 'continuous', fluid: true, startH: 1.5, stopH: 6.5, cls: 'Carbohydrate IV fluid', info: 'Hypoglycemia prophylaxis after insulin in kidney injury (prolonged insulin effect). Stop after 5 hours if glucose stable above 100 mg/dL; glucose hourly.', monitor: ['Glucose'], indication: 'Prevent delayed hypoglycemia after insulin', by: 'ed' },
          { key: 'albuterol_k', name: 'albuterol (PROVENTIL) nebulizer solution', dose: '10 mg', route: 'Nebulized', freq: 'once', startH: 1.0, cls: 'Beta-agonist bronchodilator', info: 'Four times the usual dose; shifts potassium into cells. Expect tremor and tachycardia; check HR before and after. Hold and call for HR above 130 or chest pain.', monitor: ['HR', 'K'], indication: 'Hyperkalemia (intracellular shift)', by: 'ed' },
          { ...C.bolus("lactated Ringer's bolus", 1000, { start: 1.2, by: 'ed', indication: 'Volume depletion / prerenal AKI' }), when: !esrd },
          { key: 'bicarb_infusion', name: 'sodium bicarbonate 150 mEq in 1,000 mL D5W infusion', dose: '125 mL/hr', rate: '125 mL/hr', mlPerHr: 125, route: 'IV', freq: 'continuous', fluid: true, startH: 2.5, stopH: 10.5, cls: 'Alkalinizing IV fluid', info: 'Isotonic bicarbonate for metabolic acidosis with volume depletion. Infuse on its own line (precipitates with calcium). Assess lungs and edema; check Na, K, calcium and bicarbonate.', monitor: ['Na', 'K'], indication: 'Metabolic acidosis (low serum bicarbonate) and volume repletion', by: 'hospitalist', when: !esrd },
          { ...C.lrMaintenance({ start: 10.5, stop: 36, rate: 100, by: 'hospitalist' }), when: !esrd, info: 'Balanced fluid (contains 4 mEq/L potassium; acceptable in hyperkalemia). Reassess volume status every shift: lungs, edema, weight, I&O; stop when euvolemic and drinking.' },
          { key: 'szc', name: 'sodium zirconium cyclosilicate (LOKELMA) packet', dose: '10 g', route: 'Oral', freq: 'TID', startH: 2.0, stopH: 50, cls: 'Potassium binder', info: 'Mix in 45 mL water and drink immediately. Lowers potassium within 1-4 hours. Contains sodium (watch edema, especially with heart failure); separate other oral drugs by 2 hours. May cause hypokalemia; hold for K below 4.0.', monitor: ['K'], hold: 'Hold and call provider for K below 4.0 mmol/L or new edema.', indication: 'Hyperkalemia (potassium removal), 48-hour course', by: 'hospitalist' },
          { key: 'furosemide_prn_aki', name: 'furosemide (LASIX) injection', dose: '40 mg', route: 'IV', freq: 'q12h', prn: true, prnInterval: 'Every 12 hours', prnFor: 'volume overload after fluids: crackles, new edema, SpO2 below 94%, or weight gain over 1 kg/24 h (call provider first)', cls: 'Loop diuretic', info: 'Only for overload; hold if dry (SBP below 100, poor skin turgor, rising BUN). Give slowly. Monitor urine output, K, Mg, creatinine.', monitor: ['BP', 'K', 'Cr'], hold: 'Hold and call provider for SBP below 100 or signs of dehydration.', indication: 'Fluid overload / potassium excretion', startH: 8, prnGiven: [], by: 'hospitalist', renal: { esrd: { avoid: true } }, when: !comp && !esrd },
          { key: 'furosemide_aki_iv', name: 'furosemide (LASIX) injection', dose: '80 mg', route: 'IV', freq: 'BID', at: ['0900', '1700'], startH: 36, stopH: 150, cls: 'Loop diuretic', info: 'Nephrology furosemide trial for oliguric ATN. Hold for SBP below 100 or volume depletion. Give slowly (ototoxicity). Monitor urine output hourly after the first dose, K, Mg, creatinine and weight.', monitor: ['BP', 'K', 'Cr', 'Mg'], hold: 'Hold and call provider for SBP below 100 or rising BUN with dry mucosa.', indication: 'Oliguric ATN: maintain urine output / volume balance', by: 'nephrology', renal: { esrd: { avoid: true } }, when: comp && !esrd },
          { key: 'sevelamer_aki', name: 'sevelamer carbonate (RENVELA) tablet', dose: '800 mg', route: 'Oral', freq: 'TID', at: ['0800', '1200', '1700'], startH: 60, stopH: 200, cls: 'Phosphate binder', info: 'Give WITH meals. Hold if not eating.', monitor: [], holdIf: ['npo'], indication: 'Hyperphosphatemia of AKI', by: 'nephrology', when: comp },
          { key: 'enoxaparin', name: 'enoxaparin (LOVENOX) injection', dose: '30 mg', route: 'Subcutaneous', freq: 'daily', anchorStart: true, startH: 6, cls: 'Anticoagulant (prophylaxis)', info: 'Renally adjusted prophylaxis dose (CrCl below 30 mL/min). Pharmacy to switch to heparin if renal function unstable or CrCl below 15. Monitor bleeding, platelets and creatinine.', monitor: ['Hgb', 'Plt', 'Cr'], hold: 'Hold and notify provider for active bleeding or platelets below 50.', indication: 'VTE prophylaxis (renally dosed)', by: 'hospitalist', highAlert: true, renal: { esrd: { avoid: true, sub: { key: 'heparin_ppx', name: 'heparin injection', dose: '5,000 units', freq: 'q8h', anchorStart: false, cls: 'Anticoagulant (prophylaxis)', info: 'Preferred over enoxaparin in ESRD. Monitor bleeding and platelets.' } } } },
          { key: 'acetaminophen_prn', name: 'acetaminophen (TYLENOL) tablet', dose: '650 mg', route: 'Oral', freq: 'q6h', prn: true, prnInterval: 'Every 6 hours', prnFor: 'back pain or headache (NO NSAIDs)', cls: 'Non-opioid analgesic', info: 'Maximum 3 g/day. Replaces ibuprofen/NSAIDs, which are held for AKI.', monitor: ['Pain'], indication: 'Pain (NSAID alternative)', startH: 3, prnGiven: [], by: 'hospitalist' },
          C.ondansetron({ start: 0.8, given: [1.6], by: 'ed' })
        ],
        orders: [
          C.diet('Renal diet: 2 g potassium, 2 g sodium, low phosphorus', 3, undefined, 'Avoid bananas, oranges, tomatoes, potatoes, salt substitutes (potassium chloride). Encourage oral fluids unless restricted.'),
          C.activity('Bed rest with assistance until orthostatic vitals normal', 0.5, 12, 'Weakness and orthostasis; fall precautions.'),
          C.activity('Up with assistance; ambulate in hall three times daily', 12, undefined, 'Check orthostatic BP before first ambulation.'),
          { name: 'Continuous cardiac monitoring (telemetry)', category: 'Nursing', frequency: 'Continuous', startH: 0.5, stopH: 40, instructions: 'Watch for peaked T waves, wide QRS, bradycardia or arrhythmia; notify provider immediately. Discontinue when K below 5.5 on two checks and ECG normal.' },
          { name: 'Point-of-care glucose after insulin', category: 'Lab / Bedside Testing', frequency: 'Every 1 hour for 6 hours, then every 4 hours for 24 hours', startH: 1.0, stopH: 30, instructions: 'Treat glucose below 70 mg/dL per hypoglycemia protocol (D50 25 g IV if unable to swallow); renal impairment prolongs insulin effect.' },
          { name: 'Strict intake and output', category: 'Nursing', frequency: `Every shift (goal urine output at least ${uopGoal} mL/hr)`, startH: 0.5, instructions: `${esrd ? 'Oliguric at baseline; record all urine.' : `Use a urinal/hat or commode measuring device; notify provider for urine output below ${uopGoal} mL/hr for 2 consecutive hours or no void in 6 hours.`}`, nursing: ['Bladder scan if no void in 6 hours or suprapubic fullness before calling for a catheter.'] },
          { name: 'Daily weight', category: 'Nursing', frequency: 'Daily', startH: 3, instructions: 'Same scale, same time each morning, before breakfast. Report gain over 1 kg in 24 h or loss with dizziness.' },
          { name: 'Orthostatic blood pressure and heart rate', category: 'Nursing', frequency: 'Daily and before first ambulation', startH: 6, stopH: 72, instructions: 'Lying, sitting, standing at 1 and 3 minutes; notify provider for SBP drop 20 or more, HR rise 30 or more, or symptoms.' },
          { name: 'Bladder scan: post-void residual', category: 'Nursing', frequency: 'Once, then PRN no void in 6 hours', startH: 1.0, completeH: 2.0, instructions: 'Rule out retention before considering a urinary catheter (post-renal cause).' },
          { name: 'Avoid nephrotoxins: hold NSAIDs, ACE inhibitors/ARBs, diuretics, metformin and IV contrast', category: 'Nursing', frequency: 'Continuous', startH: 0.5, instructions: 'Question any NSAID, aminoglycoside, contrast or ACE-I/ARB order. Pharmacy to renally dose all medications.', nursing: ['Educate patient: no ibuprofen, naproxen or aspirin-containing OTC products.'] },
          { name: 'Urinalysis with microscopy, urine sodium, creatinine, urea and osmolality', category: 'Laboratory', frequency: 'Once', startH: 0.5, completeH: 1.6, instructions: 'Collect before diuretics or large fluid volumes; send together.' },
          { name: 'Repeat potassium and glucose after treatment', category: 'Laboratory', frequency: '2 hours after insulin, then every 4-6 hours until K below 5.5 twice', startH: 2.0, stopH: 24, instructions: 'Potassium can rebound as insulin effect fades (4-6 hours).' },
          { name: 'Renal dosing review (pharmacy)', category: 'Nursing', frequency: 'Daily', startH: 3, instructions: 'Re-dose all medications as creatinine changes (eGFR is unreliable during AKI).' },
          ...(comp ? [{ name: 'Indwelling urinary catheter care and daily necessity review', category: 'Nursing', frequency: 'Every shift', startH: 30, stopH: 100, instructions: 'Placed for hourly output in oliguric ATN; remove as soon as hourly measurement is no longer needed.' }] : [])
        ],
        devices: [
          { ...C.pivSecond(0.6, 'Left antecubital', '18 gauge'), when: !esrd },
          ...(comp && !esrd ? [{ deviceType: 'Tube', type: 'Foley catheter', location: 'Urethral', siteMarker: 'pelvis', placeH: 30, removeH: 100, status: 'Draining', drainage: '', assess: 'draining small amounts of amber urine; secured to thigh; no leakage' }] : [])
        ],
        assessments: [
          { fromH: 0, items: [['Neurologic', 'Level of Consciousness', 'Alert, fatigued'], ['Neurologic', 'Orientation', 'Alert and oriented x4'], ['Cardiac', 'Rhythm', ctx.has('afib') ? 'Atrial fibrillation with peaked T waves on monitor' : 'Sinus rhythm with peaked T waves on monitor'], ['Cardiac', 'Capillary Refill', '3 seconds'], ['Cardiac', 'Edema', esrd ? 'Trace pedal edema' : 'None'], ['Respiratory', 'Respiratory Effort', 'Slightly deep, unlabored'], ['GI', 'Nausea / Vomiting', 'Nausea; vomited x3 at home'], ['GI', 'Abdomen', 'Soft, mild diffuse tenderness, hyperactive bowel sounds'], ['GU', 'Urinary Elimination', esrd ? 'Minimal urine output (oliguric ESRD)' : 'Voiding small amounts; decreased output x2 days'], ['GU', 'Urine Appearance', esrd ? 'Scant, amber' : 'Dark amber, concentrated'], ['Skin', 'Skin', 'Dry mucous membranes, decreased turgor (tenting), warm'], ['Musculoskeletal / Mobility', 'Mobility', 'Generalized weakness and leg cramps; dizzy on standing'], ['Safety', 'Fall Precautions', 'Moderate risk: orthostasis and weakness; bed low, assist with all mobility']] },
          { fromH: 12, items: [['Cardiac', 'Rhythm', ctx.has('afib') ? 'Atrial fibrillation, controlled rate' : 'Normal sinus rhythm, T waves normalized'], ['Cardiac', 'Capillary Refill', 'Less than 3 seconds'], ['Skin', 'Skin', esrd ? 'Warm, dry' : 'Mucous membranes moist, turgor improving'], ['GU', 'Urine Appearance', esrd ? 'Scant, amber' : 'Amber, increasing volume'], ['Musculoskeletal / Mobility', 'Mobility', 'Weakness improving; up with assist, no orthostasis'], ['GI', 'Nausea / Vomiting', 'Resolved; tolerating liquids'], ['GI', 'Abdomen', 'Soft, non-tender'], ['Respiratory', 'Respiratory Effort', 'Unlabored, even'], ['Safety', 'Fall Precautions', 'Bed low, call light in reach, assist with first ambulation (resolving orthostasis)']] },
          { fromH: 36, items: comp ? [['GU', 'Urinary Elimination', 'Oliguric: Foley draining 20-30 mL/hr'], ['GU', 'Urine Appearance', 'Dark, tea-colored'], ['Cardiac', 'Edema', 'Trace bilateral pedal edema'], ['Respiratory', 'Breath Sounds', 'Clear; fine crackles at the bases after fluids, monitor'], ['Neurologic', 'Level of Consciousness', 'Alert, mildly fatigued']] : [['GU', 'Urinary Elimination', esrd ? 'Minimal urine output (oliguric ESRD)' : 'Voiding adequate amounts'], ['GU', 'Urine Appearance', esrd ? 'Scant, amber' : 'Light yellow'], ['Cardiac', 'Edema', esrd ? 'Trace pedal edema' : 'None']] },
          { fromH: 60, items: comp ? [['Cardiac', 'Edema', '1+ pitting edema of both ankles'], ['Respiratory', 'Breath Sounds', 'Clear'], ['Skin', 'Skin', 'Warm, dry; pruritus mild'], ['GI', 'Nausea / Vomiting', 'Intermittent nausea; appetite poor']] : [['Musculoskeletal / Mobility', 'Mobility', 'Ambulating independently in hall'], ['GU', 'Urine Appearance', 'Clear, yellow']] },
          { fromH: 120, items: comp ? [['GU', 'Urinary Elimination', 'Urine output increasing (recovery phase); Foley out and voiding'], ['GU', 'Urine Appearance', 'Light yellow, large volumes'], ['Cardiac', 'Edema', 'Trace'], ['GI', 'Nausea / Vomiting', 'None; eating 75%'], ['Musculoskeletal / Mobility', 'Mobility', 'Deconditioned; ambulating with standby assist']] : [] }
        ].filter(f => f.items.length),
        io: comp
          ? [{ fromH: 0, po: 120, urine: 140 }, { fromH: 6, po: 220, urine: 180 }, { fromH: 24, po: 300, urine: 110 }, { fromH: 60, po: 380, urine: 150 }, { fromH: 120, po: 480, urine: 700 }, { fromH: 168, po: 560, urine: 620 }, { fromH: 240, po: 560, urine: 420 }]
          : [{ fromH: 0, po: 120, urine: 150 }, { fromH: 6, po: 240, urine: 220 }, { fromH: 12, po: 360, urine: 330 }, { fromH: 30, po: 450, urine: 430 }, { fromH: 54, po: 520, urine: 560 }, { fromH: 78, po: 600, urine: 500 }],
        stickies: [{ fromH: 24, title: 'Kidney protection', body: `Hold ACE-I/ARB, NSAIDs, diuretics (unless ordered) and contrast. Strict I&O (goal at least ${uopGoal} mL/hr), daily weight, renal diet. Report urine output below goal, weight gain, weakness or palpitations.` }],
        therapy: { fromH: comp ? 100 : 54 },
        discharge: { estimate: comp ? 'delayed by slow renal recovery; reassess daily' : 'day 4-5 once creatinine and potassium are stable and falling' },
        stages: [
          { fromH: 0, id: 'hyperk', label: 'Hyperkalemia with ECG changes', problem: esrd ? 'Hyperkalemia (K 6.4) with peaked T waves after missed dialysis.' : 'Prerenal AKI with hyperkalemia (K 6.4), peaked T waves and metabolic acidosis.',
            subj: 'Weak, nauseated, thirsty and dizzy when standing. Little urine for two days. Palpitations settled after treatment.',
            assess: esrd ? 'Hyperkalemia with ECG changes; needs urgent dialysis plus temporizing therapy.' : 'Prerenal AKI from volume depletion and NSAID/ACE-I with life-threatening hyperkalemia; no obstruction expected; acidosis present.',
            plan: ['Calcium gluconate for membrane stabilization, then insulin with dextrose and albuterol; recheck K 2 hours later and every 4-6 hours.', esrd ? 'Urgent hemodialysis with nephrology; low-potassium renal diet.' : 'IV fluids (LR bolus, isotonic bicarbonate), sodium zirconium cyclosilicate; stop NSAID and ACE inhibitor.', 'Continuous telemetry; hourly glucose x6 hours after insulin.', `Strict I&O, urine output goal at least ${uopGoal} mL/hr; renal ultrasound; urine studies.`, 'Nephrology consult.'],
            nursing: ['K 6.4 with peaked T waves; continuous ECG monitoring, calcium gluconate given over 10 minutes.', 'Insulin 10 units + D50 and albuterol 10 mg given; hourly glucose checks for 6 hours.', 'Dry mucous membranes, tenting; orthostatic; fall precautions and assist x1.', 'Urine dark and scant; strict I&O started; no Foley (bladder scan residual low).'],
            teach: ['Why potassium is dangerous to the heart, why treatments are timed and re-checked, and avoiding NSAIDs.'],
            dispo: `Anticipate 3-5 days${esrd ? ' with dialysis' : '; discharge when creatinine and potassium are falling and drinking well'}.`,
            stickies: [{ title: 'Hyperkalemia / AKI', body: 'K 6.4 on admission: telemetry, recheck K after insulin (rebound at 4-6 h), hourly glucose x6 h. NO NSAIDs, ACE-I/ARB or contrast. Strict I&O.' }] },
          { fromH: 10, id: 'treated', label: 'Potassium controlled; rehydrating', problem: 'AKI with hyperkalemia, treated; creatinine still rising.',
            subj: 'Less weak and no more nausea. Drinking fluids. Urinating more.',
            assess: 'K 5.0-5.6 after treatment and binder; ECG normalized; creatinine peaking as expected after prerenal insult.',
            plan: ['Continue sodium zirconium cyclosilicate; repeat K every 4-6 hours until below 5.5 twice, then daily.', 'LR 100 mL/hr until euvolemic then oral hydration; reassess lungs, edema and weight each shift.', 'Furosemide only if volume overloaded (call provider first).', 'Hold lisinopril/NSAIDs; renal diet; daily weights.'],
            nursing: ['K 5.3-5.6 on repeat; no recurrent ECG changes; glucose 80-110 after insulin/dextrose, no hypoglycemia.', 'Intake and output tracked; urine output above goal; weight recorded.', 'Orthostatic precautions continued.'],
            teach: ['Low-potassium renal diet, hydration goals, and sick-day rules (hold ACE-I and NSAIDs when vomiting or not drinking).'],
            dispo: 'Discharge in 2-3 days if creatinine peaks and falls.' },
          { fromH: 30, id: comp ? 'atn' : 'peak', label: comp ? 'Creatinine plateau: evolving ATN' : 'Creatinine peaks; urine output increasing', problem: comp ? 'AKI evolving to acute tubular necrosis (muddy brown casts, FeNa 2.4%), oliguric; K controlled.' : 'Prerenal AKI, creatinine peaked and starting to fall.',
            subj: comp ? 'Feeling tired; still making little urine despite fluids. Mild nausea and ankle swelling developing.' : 'Feels much better, eating and drinking. Voiding more.',
            assess: comp ? 'Persistent oliguria and rising BUN after fluid resuscitation: ATN. No dialysis indication (K normal on binder, no volume overload or uremia) but monitored daily.' : 'Creatinine peaked at about 24 hours and is now falling; potassium normal; acidosis resolving.',
            plan: comp ? ['Stop IV fluids to avoid overload; furosemide 80 mg IV BID trial with nephrology; Foley for hourly output.', 'Daily weights, strict I&O, BMP/phosphorus/Mg daily; renally dose all drugs.', 'Dialysis indications reviewed daily: refractory K, acidosis, overload, uremic symptoms.', 'Sevelamer with meals if phosphorus stays high.'] : ['Stop IV fluids when euvolemic; encourage oral fluids 2 L/day.', 'Telemetry stopped once K stable; BMP daily.', 'Continue to hold ACE inhibitor/NSAIDs; renal dosing of all medications.', 'PT evaluation for deconditioning.'],
            nursing: comp ? ['Foley draining 20-30 mL/hr; urine tea-colored; weight +1.2 kg.', 'Trace ankle edema; lungs with fine basilar crackles; monitor SpO2.', 'Furosemide response documented hourly after dose.'] : ['Afebrile, BP 116/70, HR 84; ambulating with assist.', 'Urine output above goal; oral intake improving.'],
            teach: ['Kidney recovery timeline, why some medications are held, daily weight and I&O role.'],
            dispo: comp ? 'Anticipate prolonged stay (kidney recovery over 1-2 weeks).' : 'Discharge in 1-2 days if creatinine continues to fall.' },
          { fromH: comp ? 120 : 56, id: 'recovery', label: comp ? 'Recovery phase: polyuria' : 'Creatinine falling; discharge planning', problem: comp ? 'ATN in recovery phase with increasing urine output.' : 'AKI resolving; creatinine falling toward baseline.',
            subj: comp ? 'Urinating large amounts; edema improving; appetite returning.' : 'Back to eating normally; energy returning; no cramps or nausea.',
            assess: comp ? 'Diuretic phase of ATN: monitor for volume depletion, hypokalemia and hypomagnesemia.' : 'Creatinine falling toward baseline with normal K; ready for discharge soon.',
            plan: comp ? ['Match fluids to losses; replace K/Mg/phosphorus as needed; stop furosemide when output adequate.', 'Remove Foley when no longer needed; PT/OT for deconditioning.', 'Nephrology follow-up 1 week with BMP.'] : ['Discharge when Cr below 2.0 and falling, K normal on 2 checks, drinking well.', 'ACE inhibitor/NSAIDs stay held; PCP/nephrology recheck BMP in 3-5 days.'],
            nursing: comp ? ['Urine output 150-200 mL/hr; weights falling; K and Mg per lab.', 'Foley removed, voiding.'] : ['Voiding clear yellow urine; eating 75-100%; ambulating independently.'],
            teach: ['Avoid NSAIDs permanently; sick-day rules; hydration; when to call (decreased urine, swelling, weakness).'],
            dispo: comp ? 'Discharge when creatinine falling steadily and mobility/home plan safe.' : 'Discharge in 1-2 days.' },
          { fromH: comp ? 200 : 86, id: 'ready', label: 'Stable: discharge planning', problem: 'Kidney injury resolving; hyperkalemia resolved.',
            subj: 'Feels well; eating and drinking; no cramps.',
            assess: 'Stable for discharge with outpatient lab recheck.',
            plan: ['Discharge home; hold ACE inhibitor/ARB and NSAIDs until PCP or nephrology reviews labs.', 'BMP within 3-5 days; nephrology follow-up 1-2 weeks.', 'Return precautions: little urine, swelling, weakness, palpitations, vomiting/diarrhea.'],
            nursing: ['Cr and K improved; teach-back done on NSAID avoidance, hydration and low-potassium diet; remove IV.'],
            teach: ['Written list of medications to avoid; sick-day plan; lab appointment.'],
            dispo: 'Discharge home today.', stickies: [{ title: 'Discharge planning', body: 'Teach-back: no NSAIDs, hold ACE-I/ARB until cleared, repeat BMP in 3-5 days.' }] }
        ],
        objectives: ['Recognize hyperkalemia ECG changes and sequence emergency treatment (calcium, shift, remove) with monitoring for rebound and hypoglycemia.', 'Interpret creatinine, BUN, urine studies and urine output to distinguish prerenal AKI from ATN and avoid nephrotoxins.', 'Perform strict I&O, daily weights and volume assessment; make a Foley decision using bladder scan and urine output goals.']
      };
      return spec;
    }
  };

  // ============================================================================ CELLULITIS (right lower leg, small abscess)
  NS.PRIMARY.cellulitis = {
    key: 'cellulitis', label: 'Lower Extremity Cellulitis', group: 'Medical', cat: 'Infectious Disease', typicalLOS: [2, 4],
    desc: 'Right lower leg cellulitis with small abscess: fever, leukocytosis, IV vancomycin, marked erythema borders, ultrasound, bedside I&D with culture (MRSA or MSSA). Day 2-4: oral step-down and discharge. Diabetic foot work-up if diabetes is selected.',
    build(ctx) {
      const fn = String(ctx.input.facultyNotes || '');
      const mrsa = /mssa/i.test(fn) ? false : /mrsa/i.test(fn) ? true : (U.hashString(String(ctx.input.mrn || ctx.input.name || '') + 'cx') % 3 !== 0);
      const dm = ctx.has('dm2'), penAllergy = ctx.allergic('penicillin');
      const useDoxy = ctx.allergic('sulfa') || ctx.has('htn') || ctx.has('hf') || ctx.renal !== 'none';   // TMP-SMX raises potassium with ACE inhibitors / kidney disease
      const idH = 9, cxH = 50, poH = 62;
      const vLoad = Math.min(3000, Math.max(1500, Math.round(ctx.weightKg * 25 / 250) * 250)), vMaint = Math.min(2000, Math.max(1000, Math.round(ctx.weightKg * 15 / 250) * 250));
      const fmt = n => n.toLocaleString();
      const vancRenal = { ckd3: { dose: '1,000 mg', freq: 'q24h', note: 'Interval extended for reduced GFR; pharmacy doses by level/AUC.' }, esrd: { dose: '750 mg', freq: 'q24h', note: 'ESRD: pharmacy doses by random level, given after dialysis; hold until the pre-dose level is reviewed.' } };
      const vancInfo = 'Infuse over at least 90-120 minutes (rate no faster than 1 g/hr) to avoid vancomycin infusion reaction (flushing, itching, hypotension). Dosed by AUC (goal 400-600) or trough (10-20). Nephrotoxic and ototoxic: monitor creatinine daily and urine output; report ringing in ears.';
      const spec = {
        primaryTeam: 'hospitalist', typicalLOS: [2, 4],
        problem: { name: 'Cellulitis of the right lower leg with abscess', details: `Right lower leg cellulitis with a small abscess${dm ? ' in a patient with diabetes (foot examined)' : ''}; ${mrsa ? 'MRSA' : 'MSSA'} on wound culture.` },
        chief: 'Red, painful, swollen right leg with fever',
        hpi: `${ctx.age}-year-old ${ctx.sex.toLowerCase()} with 4 days of an enlarging red, hot, painful area on the right lower leg after a scratch${dm ? ' (also a small blister on the right great toe)' : ''}, now with fever to 101.6 F, chills and difficulty bearing weight. Redness spread over the last 36 hours beyond the border drawn at an urgent care visit. No antibiotics before arrival. No chest pain, dyspnea, calf swelling above the knee, or numbness. Skin marker used in the ED to outline the erythema; a tender fluctuant area is present on the anterior shin.`,
        ros: 'Positive for fever, chills, leg pain, redness, swelling and malaise. Negative for chest pain, shortness of breath, vomiting, diarrhea, numbness, new rash elsewhere and recent travel or animal bites.',
        keyLabs: ['WBC', 'CRP', 'Creatinine', 'Glucose', 'Lactate', 'Vancomycin trough'], hpLabs: ['WBC', 'Creatinine', 'Glucose', 'Lactate', 'CRP', 'ESR'],
        isolation: 'None', fluidSensitive: false, fallRiskBoost: 1,
        flags: { npo: [] },
        vitals: [
          { h: 0, temp: 101.6, hr: 106, sbp: 134, dbp: 80, rr: 20, spo2: 97, pain: 7, o2: 'Room air' }, { h: 5, temp: 101.0, hr: 100, sbp: 132, dbp: 78, rr: 18, spo2: 97, pain: 6 },
          { h: 12, temp: 100.4, hr: 94, sbp: 130, dbp: 78, rr: 18, spo2: 97, pain: 4 }, { h: 24, temp: 99.8, hr: 88, sbp: 128, dbp: 76, rr: 16, spo2: 97, pain: 3 },
          { h: 36, temp: 99.0, hr: 84, sbp: 126, dbp: 76, rr: 16, spo2: 98, pain: 2 }, { h: 54, temp: 98.6, hr: 80, sbp: 124, dbp: 74, rr: 16, spo2: 98, pain: 2 }, { h: 80, temp: 98.4, hr: 76, sbp: 122, dbp: 74, rr: 16, spo2: 98, pain: 1 }
        ],
        labs: {
          WBC: { abs: [[0, 15.8], [24, 14.2], [48, 11.4], [72, 9.1], [100, 7.8]] }, CRP: { abs: [[0, 128], [24, 162], [48, 98], [96, 42]] }, ESR: { abs: [[0.5, dm ? 62 : 46], [72, dm ? 55 : 38]] },
          Lactate: { abs: [[0.5, 1.4]] }, Procalcitonin: { abs: [[0.5, 0.3]] }, Glucose: { add: [[0, 14], [48, 4], [80, 0]] }, Platelets: { add: [[0, 40], [48, 20]] },
          'Vancomycin trough': { abs: [[40, ctx.renal === 'none' ? 14.8 : 18.2]] }
        },
        labSchedule: [{ h: 0.5, codes: ['Lactate', 'CRP', 'ESR', 'Procalcitonin'] }, { h: 40, codes: ['Vancomycin trough', 'CRP'] }, { h: 74, codes: ['CRP'] }],
        quals: [
          { h: 14, category: 'Microbiology', code: 'Blood cultures x2', value: 'No growth at 12 hours', specimen: 'Blood', status: 'Preliminary' },
          { h: 50, category: 'Microbiology', code: 'Blood cultures x2', value: 'No growth at 48 hours', specimen: 'Blood', status: 'Preliminary' },
          { h: 30, category: 'Microbiology', code: 'Wound culture (abscess)', value: 'Gram-positive cocci in clusters (many WBC)', specimen: 'Abscess fluid', flag: 'Abnormal', status: 'Preliminary' },
          { h: cxH, category: 'Microbiology', code: 'Wound culture (abscess)', value: mrsa ? 'Methicillin-resistant Staphylococcus aureus (MRSA); susceptible to vancomycin, trimethoprim-sulfamethoxazole, doxycycline and clindamycin; resistant to oxacillin and cefazolin' : 'Methicillin-susceptible Staphylococcus aureus (MSSA); susceptible to oxacillin, cefazolin, doxycycline, trimethoprim-sulfamethoxazole and clindamycin', specimen: 'Abscess fluid', flag: 'Abnormal', status: 'Final' }
        ],
        events: [
          { type: 'imaging', h: 2.5, study: 'Ultrasound right lower extremity: soft tissue and venous duplex', modality: 'Ultrasound', indication: 'Cellulitis with fluctuance: evaluate for abscess; exclude DVT', findings: 'Diffuse subcutaneous edema with "cobblestoning" of the anterior lower leg. Complex hypoechoic collection with internal debris at the anterior shin measuring 2.4 x 1.3 x 1.6 cm, consistent with a small abscess. Common femoral, popliteal and calf veins are compressible with normal flow; no deep vein thrombosis.', impression: 'Small subcutaneous abscess (2.4 cm) within cellulitis. No DVT.' },
          ...(dm ? [{ type: 'imaging', h: 3.2, study: 'X-ray right foot, 3 views', modality: 'X-ray', indication: 'Diabetes with great toe blister and cellulitis: exclude osteomyelitis or gas', findings: 'Soft tissue swelling of the dorsal foot and ankle. No subcutaneous gas, foreign body, cortical erosion or periosteal reaction. Mild vascular calcification.', impression: 'No radiographic osteomyelitis or soft tissue gas.' }] : []),
          { type: 'transfer', h: 4.0, label: 'Admitted to the medical unit', text: 'Transferred from the ED to the medical unit.' },
          { type: 'procedure', h: idH, duration: 0.5, name: 'Bedside incision and drainage of right shin abscess', label: 'I&D of right shin abscess', by: 'hospitalist', service: 'Hospital Medicine', indication: 'Abscess within cellulitis (ultrasound confirmed)', findings: 'Time-out performed; 1% lidocaine local anesthesia. 1.5 cm incision over the fluctuance; about 5 mL of thick yellow-tan purulent fluid drained, loculations broken with a hemostat, irrigated with saline and loosely packed with 1/4-inch iodoform gauze. Culture sent. Dressed with absorbent gauze.' },
          ...(dm ? [{ type: 'consult', h: 20, service: 'Podiatry', author: 'K. Vance, DPM (Podiatry)', reason: 'Diabetic foot: cellulitis with toe blister', label: 'Podiatry consulted', recommendation: 'No osteomyelitis on x-ray; blister unroofed and debrided at bedside, no probe-to-bone. Offload the foot, daily foot checks, ABI/pulse check, glycemic control (goal 140-180), and podiatry follow-up in 1 week.' }] : [])
        ],
        meds: [
          { key: 'vancomycin_load', name: 'vancomycin IVPB', dose: `${fmt(vLoad)} mg`, route: 'IV', freq: 'once', startH: 0.9, volume: 500, cls: 'Glycopeptide antibiotic', info: `Weight-based loading dose (25 mg/kg). ${vancInfo}`, monitor: ['Temp', 'WBC', 'Cr'], indication: 'Purulent cellulitis with abscess (empiric MRSA coverage)', by: 'ed', highAlert: true },
          { key: 'vancomycin', name: 'vancomycin IVPB', dose: `${fmt(vMaint)} mg`, route: 'IV', freq: 'q12h', startH: 12.9, stopH: mrsa ? poH : cxH, volume: 250, cls: 'Glycopeptide antibiotic', info: vancInfo, monitor: ['Temp', 'WBC', 'Cr'], hold: 'Hold and call pharmacy/provider for creatinine rise of 0.3 mg/dL or more, urine output drop, or vancomycin level above 20 mcg/mL.', indication: mrsa ? 'MRSA abscess/cellulitis (until oral step-down)' : 'Purulent cellulitis (until culture result)', by: 'hospitalist', highAlert: true, renal: vancRenal },
          ...(mrsa ? [] : [{ key: 'cefazolin', name: 'cefazolin IVPB', dose: '2 g', route: 'IV', freq: 'q8h', startH: cxH, stopH: poH, volume: 100, cls: 'Cephalosporin antibiotic', info: 'De-escalated from vancomycin for MSSA. Infuse over 30 minutes. Monitor for rash and diarrhea (C. difficile).', monitor: ['Temp', 'WBC'], indication: 'MSSA cellulitis/abscess (targeted therapy)', by: 'hospitalist', avoid: ['penicillin'], renal: { ckd3: { dose: '2 g', freq: 'q12h', note: 'Interval extended for reduced GFR.' }, esrd: { dose: '1 g', freq: 'q24h', note: 'ESRD dosing; give after dialysis.' } }, alt: { key: 'vancomycin_cont', name: 'vancomycin IVPB', dose: `${fmt(vMaint)} mg`, freq: 'q12h', volume: 250, cls: 'Glycopeptide antibiotic', info: `Vancomycin continued because of penicillin allergy (no beta-lactam de-escalation). ${vancInfo}`, monitor: ['Temp', 'WBC', 'Cr'], highAlert: true, renal: vancRenal } }]),
          ...(dm ? [{ key: 'pip_tazo', name: 'piperacillin-tazobactam (ZOSYN) IVPB', dose: '3.375 g', route: 'IV', freq: 'q8h', startH: 1.0, stopH: cxH, volume: 100, cls: 'Penicillin / beta-lactamase inhibitor', info: 'Diabetic foot: added gram-negative and anaerobic coverage until cultures finalize. Infuse over 4 hours (extended infusion). Combined with vancomycin raises acute kidney injury risk: monitor creatinine daily.', monitor: ['Cr', 'WBC'], indication: 'Diabetic soft tissue infection (broad empiric coverage)', by: 'ed', avoid: ['penicillin'], renal: { ckd3: { dose: '2.25 g', freq: 'q6h', note: 'Dose adjusted for reduced GFR.' }, esrd: { dose: '2.25 g', freq: 'q8h', note: 'ESRD dosing.' } }, alt: { key: 'meropenem', name: 'meropenem IVPB', dose: '1 g', cls: 'Carbapenem antibiotic', info: 'Used because of penicillin allergy (low cross-reactivity). Infuse over 30 minutes; may lower seizure threshold in renal impairment.', renal: { ckd3: { dose: '1 g', freq: 'q12h', note: 'Dose adjusted for reduced GFR.' }, esrd: { dose: '500 mg', freq: 'q24h', note: 'ESRD dosing.' } } } }] : []),
          // oral step-down
          ...(mrsa
            ? [useDoxy
              ? { key: 'doxycycline', name: 'doxycycline (VIBRA-TABS) tablet', dose: '100 mg', route: 'Oral', freq: 'BID', startH: poH, stopH: 192, cls: 'Tetracycline antibiotic', info: `Take with a full glass of water and stay upright 30 minutes (esophagitis); separate from calcium, iron and antacids by 2 hours; sun protection. Chosen instead of TMP-SMX ${ctx.allergic('sulfa') ? 'because of sulfa allergy' : 'because TMP-SMX can cause hyperkalemia and creatinine rise with ACE inhibitors/kidney disease/heart failure'}.`, monitor: ['Temp'], indication: 'Oral step-down for MRSA skin infection (complete 7-10 days)', by: 'hospitalist' }
              : { key: 'tmp_smx', name: 'sulfamethoxazole-trimethoprim (BACTRIM DS) tablet', dose: '1 tablet (800/160 mg)', route: 'Oral', freq: 'BID', startH: poH, stopH: 192, cls: 'Sulfonamide antibiotic', info: 'Encourage fluids. Raises potassium and creatinine (especially with ACE inhibitors, ARBs, spironolactone or kidney disease): check BMP. STOP and report any rash (Stevens-Johnson risk). Sun sensitivity.', monitor: ['K', 'Cr'], indication: 'Oral step-down for MRSA skin infection (complete 7-10 days)', by: 'hospitalist', avoid: ['sulfa'], alt: { key: 'doxycycline', name: 'doxycycline (VIBRA-TABS) tablet', dose: '100 mg', freq: 'BID', cls: 'Tetracycline antibiotic', info: 'Used because of sulfa allergy. Take with a full glass of water and stay upright 30 minutes; separate from calcium, iron and antacids by 2 hours; sun protection.', monitor: ['Temp'] } }]
            : [{ key: 'cephalexin', name: 'cephalexin (KEFLEX) capsule', dose: '500 mg', route: 'Oral', freq: 'QID', startH: poH, stopH: 192, cls: 'Cephalosporin antibiotic', info: 'Take with or without food; complete the full course (total 7-10 days). Report rash, severe diarrhea (C. difficile) or swelling of lips/face.', monitor: ['Temp', 'WBC'], indication: 'Oral step-down for MSSA cellulitis', by: 'hospitalist', avoid: ['penicillin'], renal: { ckd3: { dose: '500 mg', freq: 'TID', note: 'Interval extended for reduced GFR.' }, esrd: { dose: '500 mg', freq: 'BID', note: 'ESRD dosing; give after dialysis.' } }, alt: { key: 'doxycycline', name: 'doxycycline (VIBRA-TABS) tablet', dose: '100 mg', freq: 'BID', cls: 'Tetracycline antibiotic', info: 'Used because of penicillin allergy. Take with a full glass of water and stay upright 30 minutes; separate from calcium, iron and antacids by 2 hours; sun protection.', monitor: ['Temp'], renal: {} } }]),
          { key: 'acetaminophen', name: 'acetaminophen (TYLENOL) tablet', dose: '650 mg', route: 'Oral', freq: 'q6h', startH: 1.0, stopH: 96, cls: 'Non-opioid analgesic / antipyretic', info: 'Maximum 3 g per 24 hours from all sources. Scheduled for pain and fever; record temperature before giving and do not let it mask a fever trend.', monitor: ['Temp', 'Pain'], indication: 'Pain / fever', by: 'ed' },
          C.opioidPO(ctx, { start: 2.0, given: [3.5, 8.5, 22], by: 'ed', stop: 96 }),
          { key: 'ondansetron', name: 'ondansetron (ZOFRAN) injection', dose: '4 mg', route: 'IV', freq: 'q8h', prn: true, prnInterval: 'Every 8 hours', prnFor: 'nausea', cls: 'Antiemetic (5-HT3 antagonist)', info: 'QT-prolonging; check electrolytes.', monitor: ['K', 'Mg'], indication: 'Nausea', startH: 1.0, prnGiven: [], by: 'ed' }
        ],
        orders: [
          C.diet('Regular diet', 3, undefined, 'Encourage protein and oral fluids to support wound healing.'),
          C.activity('Bed rest with right leg elevated; bathroom privileges with assistance', 0.5, 24, 'Elevate leg on pillows above heart level; fall precautions (pain, opioid).'),
          C.activity('Up with assistance; ambulate in hall three times daily', 24, undefined, 'Elevate leg when seated or in bed; early mobility; use walking aid as needed.'),
          { name: 'Elevate right leg above heart level', category: 'Nursing', frequency: 'Continuous when in bed or chair', startH: 0.5, instructions: 'Pillows under calf and foot (not behind the knee); reduces edema and pain.' },
          { name: 'Mark erythema borders with skin marker; measure; reassess every shift', category: 'Nursing', frequency: 'On arrival and every shift (every 8-12 hours)', startH: 1.0, instructions: 'Outline the edge of the redness with a skin marker; record date, time, initials and size (length x width in cm). Compare each shift. Notify provider if redness spreads past the line, new blisters/bullae, dusky or purple skin, crepitus, pain out of proportion to appearance, numbness, or fever/hypotension (possible necrotizing infection).', nursing: ['Photograph per policy; keep the same landmark measurements each shift.', 'Recheck the borders 12-24 hours after the first antibiotic dose; slight early spread can occur.'] },
          { name: 'Neurovascular and skin check, right leg', category: 'Nursing', frequency: 'Every 4 hours for 24 hours, then every shift', startH: 1.0, instructions: 'Pulses (dorsalis pedis, posterior tibial), capillary refill, sensation, movement, warmth, calf firmness; check for bullae and compartment tightness.' },
          { name: 'Blood cultures x2', category: 'Laboratory', frequency: 'Once, before the first antibiotic dose', startH: 0.2, completeH: 0.8, instructions: 'Two sets from separate sites.' },
          { name: 'Wound culture of abscess fluid', category: 'Laboratory', frequency: 'Once at incision and drainage', startH: idH - 0.5, completeH: idH + 0.5, instructions: 'Send purulent drainage in a sterile container or aerobic culture swab; do not culture the skin surface.' },
          { name: 'Vancomycin level (trough or AUC-guided)', category: 'Laboratory', frequency: 'Once before the 4th dose', startH: 20, completeH: 40, instructions: 'Draw 30 minutes before the dose; record exact time of the previous dose.' },
          { name: 'Wound care: I&D site packing and dressing', category: 'Nursing', frequency: 'Daily and PRN when saturated', startH: idH + 0.6, instructions: 'Provider removes the packing at 24-48 hours; then rinse with saline and apply an absorbent dressing (or repack per provider). Document drainage amount/color/odor and wound size.', nursing: ['Use standard precautions with drainage; dispose of soiled dressings in biohazard bag.'] },
          { name: 'Verify tetanus immunization', category: 'Nursing', frequency: 'Once', startH: 3, instructions: 'Give Tdap if last tetanus booster was more than 5 years ago or unknown (open abscess/wound).' },
          { name: 'Intake and output; encourage oral fluids', category: 'Nursing', frequency: 'Every shift', startH: 3, instructions: 'Goal 2 L oral fluids per day unless restricted.' },
          { name: 'Fall precautions (pain, opioid, leg weakness)', category: 'Precautions', frequency: 'Continuous', startH: 1.0, instructions: 'Assist with first ambulation; check pain and sedation before walking.' },
          ...(mrsa ? [{ name: 'Contact precautions (MRSA wound drainage)', category: 'Precautions', frequency: 'Continuous', startH: 30, instructions: 'Gown and gloves for contact with the patient and wound; dedicated equipment; hand hygiene with soap and water or alcohol rub; sign on door.' }] : []),
          ...(dm ? [
            { name: 'Diabetic foot exam and offloading', category: 'Nursing', frequency: 'Daily', startH: 3, instructions: 'Inspect both feet and between toes daily; protect heels; no barefoot walking; monofilament and pulse check documented.' },
            { name: 'Ankle-brachial index or pulse Doppler, right leg', category: 'Cardiac Testing', frequency: 'Once', startH: 6, completeH: 24, instructions: 'Assess perfusion for healing; vascular referral if ABI below 0.9.' }
          ] : []),
          { name: 'Discharge teaching: wound care and antibiotic adherence', category: 'Nursing', frequency: 'Once before discharge', startH: poH - 6, instructions: 'Teach-back: antibiotic schedule, wound care, leg elevation, signs of worsening (spreading redness, fever, pus), follow-up in 48-72 hours.' }
        ],
        devices: [C.pivSecond(0.6, 'Left antecubital', '20 gauge')],
        assessments: [
          { fromH: 0, items: [['Skin', 'Skin', 'Right anterior lower leg: erythema 14 x 9 cm, warm, tender, indurated with 2+ pitting edema; borders marked with skin marker; 2 cm fluctuant area at mid-shin; no bullae or crepitus'], ['Skin', 'Braden Score', '20'], ['Cardiac', 'Capillary Refill', 'Less than 3 seconds; right DP and PT pulses palpable (2+)'], ['Cardiac', 'Edema', 'Right lower leg 2+ pitting edema to the ankle; left none'], ['Cardiac', 'Rhythm', ctx.has('afib') ? 'Atrial fibrillation' : 'Sinus tachycardia'], ['Pain', 'Pain Location', 'Right lower leg, throbbing, 7/10, worse with standing'], ['Musculoskeletal / Mobility', 'Mobility', 'Antalgic gait; limited by pain; up with assistance'], ['Neurologic', 'Level of Consciousness', 'Alert'], ...(dm ? [['Safety', 'Diabetes Care', 'Glucose checks per order; right great toe 0.5 cm intact blister, surrounding erythema; no ulcer, foot pulses palpable']] : [])] },
          { fromH: 12, items: [['Skin', 'Skin', 'Right shin: erythema 14 x 9 cm, unchanged from marked border; I&D site with packing in place, moderate serosanguineous-purulent drainage; leg elevated'], ['Pain', 'Pain Location', 'Right lower leg, 4/10 after drainage'], ['Cardiac', 'Rhythm', ctx.has('afib') ? 'Atrial fibrillation' : 'Normal sinus rhythm']] },
          { fromH: 30, items: [['Skin', 'Skin', 'Right shin: erythema receded to 11 x 7 cm (inside marked border); less warm; I&D wound 1.5 cm, packing removed, scant serous drainage, no odor; blanching'], ['Cardiac', 'Edema', 'Right lower leg 1+ pitting edema'], ['Pain', 'Pain Location', 'Right shin, 3/10'], ['Musculoskeletal / Mobility', 'Mobility', 'Walking in hall with minimal assistance; mild limp']] },
          { fromH: 54, items: [['Skin', 'Skin', 'Right shin: erythema 6 x 4 cm and fading, no longer warm; I&D wound granulating, minimal clear drainage'], ['Cardiac', 'Edema', 'Trace right ankle edema'], ['Pain', 'Pain Location', 'Right shin, 2/10 with walking only'], ['Musculoskeletal / Mobility', 'Mobility', 'Ambulating independently']] },
          { fromH: 80, items: [['Skin', 'Skin', 'Right shin: faint pink residual 3 x 2 cm, cool; wound clean, dry dressing'], ['Cardiac', 'Edema', 'None to trace'], ['Pain', 'Pain Location', 'None to mild with walking']] }
        ],
        io: [{ fromH: 0, po: 240, urine: 330 }, { fromH: 12, po: 400, urine: 380 }, { fromH: 30, po: 480, urine: 400 }],
        therapy: { fromH: 26, rec: 'Home; no therapy needs beyond early mobility', pt: ctx.age >= 70 },
        discharge: { estimate: 'day 3-4 once afebrile 24 hours, erythema receding and tolerating oral antibiotics' },
        stages: [
          { fromH: 0, id: 'acute', label: 'Febrile cellulitis with abscess', problem: 'Right lower leg cellulitis with small abscess; febrile with leukocytosis.',
            subj: 'Throbbing, hot red leg; pain 7/10; chills. Can barely walk.',
            assess: 'Purulent cellulitis (skin and soft tissue infection) with a 2.4 cm abscess on ultrasound; no DVT; hemodynamically stable (no sepsis); lactate normal.',
            plan: ['Vancomycin IV (MRSA coverage) after blood cultures; level/AUC-guided with daily creatinine.', 'Bedside incision and drainage of abscess with wound culture.', 'Mark erythema borders and reassess every shift; elevate leg; acetaminophen and oxycodone for pain.', 'Watch for necrotizing infection signs (pain out of proportion, bullae, dusky skin, rising lactate/hypotension).', dm ? 'Diabetes: foot x-ray, podiatry, broad coverage with pip-tazo, glucose goal 140-180, ABI.' : 'Verify tetanus status.'],
            nursing: ['T 101.6 F, HR 106; erythema 14 x 9 cm marked with skin marker; leg elevated.', 'Blood cultures x2 drawn before vancomycin; IV access x2.', 'Neurovascular checks every 4 hours: pulses 2+, sensation intact.', 'Pain 7/10; acetaminophen scheduled with oxycodone PRN; fall precautions.'],
            teach: ['Why borders are marked and measured, leg elevation, and when to report spreading redness.'],
            dispo: 'Anticipate 2-4 days; discharge when afebrile and on oral antibiotics.',
            stickies: [{ title: 'Cellulitis: borders marked', body: 'Erythema outlined with skin marker; re-measure and compare each shift. Report spread past the line, bullae, dusky skin, severe pain, fever or low BP. Leg elevated.' }] },
          { fromH: idH + 3, id: 'post_id', label: 'After I&D: draining, fever falling', problem: 'Right shin abscess drained; cellulitis improving; culture pending.',
            subj: 'Pain much better after the drainage; chills gone. Tolerating food.',
            assess: 'Source control achieved; Tmax down overnight; erythema not spreading; wound culture pending.',
            plan: ['Continue vancomycin; follow vancomycin level and creatinine.', 'Packing removed by provider at 24-48 hours; daily dressing changes.', 'Follow wound and blood cultures.', 'Mobilize with leg elevated when resting.'],
            nursing: ['I&D site with packing; moderate drainage; dressing reinforced.', 'Erythema within the marked border; afebrile except one low-grade temperature.', 'Pain 3-4/10; up with assistance.'],
            teach: ['Wound drainage is expected; keep dressing dry; hand hygiene.'],
            dispo: 'Discharge in 1-3 days.' },
          { fromH: 30, id: 'improving', label: mrsa ? 'Improving; culture growing Gram-positive cocci' : 'Improving; Gram-positive cocci on culture', isolation: mrsa ? 'Contact precautions' : 'None', problem: 'Cellulitis improving; abscess culture growing Staphylococcus.',
            subj: 'Leg feels much less tight and hot; walking in the hall. Appetite back.',
            assess: 'Erythema receding inside marked borders; afebrile; WBC falling; preliminary culture Gram-positive cocci in clusters.',
            plan: [mrsa ? 'Contact precautions started for MRSA risk; continue vancomycin pending final susceptibilities.' : 'Continue vancomycin pending susceptibilities (de-escalate if MSSA).', 'Monitor vancomycin level and creatinine.', 'Daily wound care; continue marking and measuring.', 'Plan oral step-down when afebrile 24 hours and erythema receding.'],
            nursing: ['Erythema 11 x 7 cm, inside prior border; T 99.0 F.', 'Wound with scant serous drainage; ambulating in hall.', mrsa ? 'Contact precautions initiated; gown and gloves used for wound care.' : 'Standard precautions; wound care with clean technique.'],
            teach: ['Completing the antibiotic course, hand hygiene, not sharing towels or razors.'],
            dispo: 'Discharge anticipated within 1-2 days.' },
          { fromH: cxH, id: 'targeted', label: mrsa ? 'MRSA confirmed; planning oral step-down' : 'MSSA confirmed; de-escalation', isolation: mrsa ? 'Contact precautions' : 'None', problem: `${mrsa ? 'MRSA' : 'MSSA'} skin and soft tissue infection, improving.`,
            subj: 'Almost no pain; walking independently. Leg much less red.',
            assess: `Final culture ${mrsa ? 'MRSA' : 'MSSA'}; blood cultures no growth at 48 hours; afebrile more than 24 hours.`,
            plan: [mrsa ? 'Continue vancomycin until oral step-down; TMP-SMX or doxycycline selected by kidney function, potassium risk and allergies.' : 'Change vancomycin to cefazolin, then oral cephalexin; doxycycline if penicillin allergic.', 'Complete 7-10 days total therapy.', 'Wound check at follow-up in 48-72 hours.'],
            nursing: ['Erythema 6 x 4 cm, fading; wound granulating; afebrile.', 'Antibiotic changed per susceptibilities; teaching started.'],
            teach: [mrsa ? 'MRSA: wound care, hand hygiene, household precautions.' : 'Wound care and antibiotic schedule.'],
            dispo: 'Discharge today or tomorrow when oral antibiotic tolerated.' },
          { fromH: poH - 2, id: 'ready', label: 'On oral antibiotics: discharge planning', isolation: mrsa ? 'Contact precautions' : 'None', problem: 'Cellulitis/abscess resolving; ready for oral antibiotics at home.',
            subj: 'Feels back to normal, walking without pain.',
            assess: 'Clinically resolved to the point of discharge; faint residual erythema; wound clean.',
            plan: ['Discharge home on oral antibiotics to complete 7-10 days.', 'Wound/skin recheck with PCP in 48-72 hours; return if spreading redness, fever, pus or increasing pain.', dm ? 'Podiatry and PCP follow-up; A1c review.' : 'Compression/elevation for residual edema.'],
            nursing: ['Afebrile 48 hours; erythema 3 x 2 cm; ambulating independently.', 'Teach-back on wound care, antibiotic dosing and return precautions; IV removed.'],
            teach: ['Take the full antibiotic course; elevate leg; keep skin moisturized and treat athlete\'s foot; return precautions.'],
            dispo: 'Discharge home today.', stickies: [{ title: 'Discharge planning', body: 'Oral antibiotic teach-back; wound care; recheck in 48-72 hours.' }] }
        ],
        objectives: ['Mark, measure and reassess cellulitis borders every shift and recognize signs of necrotizing infection.', 'Administer vancomycin safely (slow infusion, level timing, renal monitoring) and apply allergy and kidney-based antibiotic swaps.', 'Care for an I&D wound, culture drainage correctly and teach step-down antibiotic adherence.']
      };
      return spec;
    }
  };
})();
